ergo-pad/ergopad-api

app/api/v1/routes/projects.py, app/db/crud/projects.py
- /5
- /project_title
- /projecttitle
=> :update: GET projects/{project_id}

.gitignore, .vscode/settings.json, app/api/v1/routes/staking.py
=> Cache Staking Status

app/db/crud/projects.py
=> :fix: projects crud error

app/api/v1/routes/whitelist.py
upd to current convention of using JSONResponse and content is NOT JSON
=> upd to jsonresponse convention

app/api/v1/routes/announcements.py, app/api/v1/routes/faq.py, app/db/crud/announcements.py, app/db/crud/faq.py, app/db/models/announcements.py, app/db/models/faq.py, app/db/schemas/announcements.py, app/db/schemas/faq.py, app/main.py
- https://docs.google.com/document/d/1DZuns6iilipxvcYm0Zpp-TmDayKOazLbxBcL0ozicGo/edit
=> :add: cms api for /faq and /announcement

app/api/v1/routes/staking.py
minor update to auth for snapshot call
=> upd auth for snapshot call

app/api/v1/routes/blockchain.py, app/api/v1/routes/staking.py, app/config.py
- added ergopadInCirculation
- added totalSupply
=> Add cmc cg specific endpoints

app/api/v1/routes/staking.py
=> :update: cache staking/staked TTL=10min

.gitignore, app/main.py, app/test/.env.test, app/test/conftest.py, app/test/test_example.py, requirements.in
-  ### run tests [dir=ergopad-api/app]
```
python3 -m pytest
```
- Integrate with github actions
=> :add: setup pytest

.github/workflows/build_test.yml, README.md, app/ergodex/price.py, requirements.in
- ### Adds CI with GitHub Actions (run all unit tests)
- ### Update README.md
=> :add: Automated Testing with GitHub Actions

app/api/v1/routes/util.py, app/cache/cache.py
-  POST ```/api/utils/forceInvalidateCache``` [super_user_only]
Invalidate redis cache key if required from api to force update something
=> :add: POST /api/utils/forceInvalidateCache

app/api/v1/routes/whitelist.py, app/core/security.py, app/test/test_whitelist.py, requirements.in
- Unit Tests Added
- Clean up whitelist code
- Fix calculations for allowances
=> :update: whitelist

app/api/v1/routes/whitelist.py, app/test/test_whitelist.py
- ### Update event name to staker-seed-paideia-202203wl
- ### Fix is Funding Calculation
- ### Check for individualCap
=> :update: whitelist.py for paideia wl event

app/api/v1/routes/blockchain.py
=> :add: caching to ergopad supply endpoints

app/api/v1/routes/blockchain.py
- Updated JSON
```
{
"boxId": "b56fed43240abe4d9def7f5dba8c114c55374f72ef36b38670a37c0768f49b39",
"additionalRegisters": {
"R4": {
"serializedValue": "11022ca0c49c97e85f",
"sigmaType": "Coll[SLong]",
"renderedValue": "[22,1646070567184]"
},
"R5": {
"serializedValue": "0e20fc4321292925b1eaaeacc80f0c2377b37cd2c5fd42037910c3cabb642f62ac85",
"sigmaType": "Coll[SByte]",
"renderedValue": "fc4321292925b1eaaeacc80f0c2377b37cd2c5fd42037910c3cabb642f62ac85"
}
},
"address": "3eiC8caSy3jiCxCmdsiFNFJ1Ykppmsmff2TEpSsXY1Ha7xbpB923Uv2midKVVkxL3CzGbSS2QURhbHMzP9b9rQUKapP1wpUQYPpH8UebbqVFHJYrSwM3zaNEkBkM9RjjPxHCeHtTnmoun7wzjajrikVFZiWurGTPqNnd1prXnASYh7fd9E2Limc2Zeux4UxjPsLc1i3F9gSjMeSJGZv3SNxrtV14dgPGB9mY1YdziKaaqDVV2Lgq3BJC9eH8a3kqu7kmDygFomy3DiM2hYkippsoAW6bYXL73JMx1tgr462C4d2PE7t83QmNMPzQrD826NZWM2c1keh …
```
=> :fix: explorer query for /staking/compound

app/api/v1/routes/vesting.py, app/ergo/appkit.py
- >0 value check
- inputBox validation
=> airdrop tweaks

app/api/v1/routes/vesting.py, app/ergo/appkit.py, app/test/test_vesting.py
=> correct sigusd tokenid stringify datainput

app/api/v1/routes/vesting.py
- inc vesting fee to avoid oracle pools
- vest key desc fix
=> vesting fee/desc

app/api/v1/routes/purchase.py, app/api/v1/routes/staking.py, app/api/v1/routes/vesting.py, app/ergo/appkit.py
- key not found, fix
- better fail
=> improved err trapping

app/api/v1/routes/blockchain.py, app/api/v1/routes/staking.py, app/ergo/appkit.py
=> fix airdrop tweaks

app/api/v1/routes/whitelist.py, app/db/crud/whitelist_events.py, app/test/test_whitelist.py
- microseconds stored in db
- check for 0 sigusd allocation
- closes #45
- Updates unit tests
```
{
"status": "success",
"data": [
{
"name": "paideia-strategic-202204wl",
"address": "9i6UmaoJKWHgWkuq1EJUoYu2hrkRkxAYwQjDotHRHfGrBo16Rss",
"email": "",
"social_handle": "__hardcoded_patch",
"social_platform": "__hardcoded_patch",
"allowance_sigusd": 10,
"ip_hash": "122c4a55d1a70cef972cac3982dd49a6",
"created_dtz": "2022-04-02T18:58:00+00:00"
},
{
"name": "paideia-strategic-202204wl",
"address": "3WzKuUxmG7HtfmZNxxHw3ArPzsZZR96yrNkTLq4i1qFwVqBXAU8X",
"email": "hello@world.com",
"social_handle": "@tweetyBird",
"social_platform": "twitter",
"allowance_sigusd": 1,
"ip_hash": "122c4a55d1a70cef972cac3982dd49a6",
"created_dtz": "2022-04-03T06:11:42+00:00"
},
{
"name": "paideia-strategic-202204wl", …
```
=> :update: whitelist signup

app/api/v1/routes/projects.py, app/db/crud/projects.py, app/db/models/projects.py, app/db/schemas/projects.py
```
{
"name": "string test",
"shortDescription": "string",
"description": "string",
"fundsRaised": 0,
"bannerImgUrl": "string",
"isLaunched": true,
"socials": {
"telegram": "string",
"twitter": "string",
"discord": "string",
"github": "string",
"website": "string",
"linkedin": "string"
},
"roadmap": {
"roadmap": [
{
"name": "string test",
"description": "string",
"date": "2022-04-08T06:11:17.544Z"
}
]
},
"team": {
"team": [
{
"name": "string",
"description": "string",
"profileImgUrl": "string",
"socials": {
"telegram": "string",
"twitter": "string",
"discord": "string",
"github": "string",
"website": "string test",
"linkedin": "string"
}
}
]
},
"tokenomics": {
"tokemomics": [
{
"name": "string",
"amount": 19,
"value": "string",
"tge": "string",
"freq": "string",
"length": "string", …
```
=> :update: projects model

app/api/v1/routes/asset.py, app/ergodex/price.py
- ergodex amm pools
- portfolio history for all token prices
=> :add: ergodex token prices

app/ergodex/price.py
=> :add: caching to ergodex amm pool box

app/api/v1/routes/vesting.py
=> Redeemwithnft cutoffexcess

app/api/v1/routes/asset.py
- request list of token names
- response current asset price list
closes #124
=> :add: new api endpoint for token prices

app/api/v1/routes/vesting.py
- all endpoints have try/catch
- better error messages (removed full message from return)
=> upd err trap with better error messages

app/api/v1/routes/vesting.py, app/requirements.txt
=> upd vesting err

app/api/v1/routes/vesting.py
- vestFromProxy
- redeemWithNFT
=> added better custom errors

app/api/v1/routes/notifications.py, app/db/crud/notifications.py, app/db/models/notifications.py, app/db/schemas/notifications.py, app/main.py
- get notifications of one address
- request: list of addresses
- same as GET
- create notifications
- delete
- clean up older notifications (30 days)
=> :add: notifications orm crud

app/db/crud/notifications.py, app/db/schemas/notifications.py
=> :update: notifications backend

app/api/v1/routes/tutorials.py, app/db/crud/contribution_events.py, app/db/crud/tutorials.py, app/db/crud/whitelist_events.py, app/db/models/tutorials.py, app/db/schemas/tutorials.py, app/main.py
- GET ```/```
- GET ```/categories```
- POST ```/```
- PUT ```/id```
- DELETE ```/id```
=> :add: tutorials cms

app/api/v1/routes/blockchain.py
=> upd "in circ" calcs

app/api/v1/routes/vesting.py
align calculation of required erg
=> aligned nergrequired

app/api/v1/routes/staking.py
Allows for more robust box picking
=> Add addresses to (un)stake endpoints

app/api/v1/routes/staking.py
- ### Adds default values for addresses
=> :add: default values for stake and unstake request

app/api/v1/routes/asset.py, app/db/session.py, app/ergodex/price.py
issue:
https://stackoverflow.com/questions/58378708/sqlalchemy-cant-reconnect-until-invalid-transaction-is-rolled-back
- better error logging
- updated caching scheme to handle error
=> :add: db rollback on transaction failure

app/api/v1/routes/asset.py, app/test/test_asset.py
=> :update: refactor asset price endpoint, add tests

app/api/v1/routes/staking.py, app/db/crud/staking_config.py, app/db/models/stakingConfig.py, app/db/schemas/stakingConfig.py
=> :add: staking config cms

app/db/crud/staking_config.py, app/db/models/stakingConfig.py, app/db/schemas/stakingConfig.py
- new schema 
```
{
"project": "string",
"title": "string",
"tokenId": "string",
"tokenDecimals": 0,
"stakingInfo": "string",
"terms": "string",
"additionalDetails": {}
}
```
=> :update: stakingConfig to include tokenDecimals

app/api/v1/routes/staking.py
=> :add: all-staked-v2 endpoint

app/api/v1/routes/staking.py
=> revert back to eval

app/api/v1/routes/staking.py, app/api/v1/routes/vesting.py
:update: caching scheme
- add caching for /vesting/vested
=> :update: caching for staking and vesting

app/api/v1/routes/staking.py, app/api/v1/routes/util.py
- limited height to lowest where staked ergopad exists
- reworked sql to be more effecient
- updated how the index was pulling
- compared the results from prod to these
=> upd logger changes

app/api/v1/routes/announcements.py, app/api/v1/routes/asset.py, app/api/v1/routes/auth.py, app/api/v1/routes/blockchain.py, app/api/v1/routes/contribution.py, app/api/v1/routes/faq.py, app/api/v1/routes/jobs.py, app/api/v1/routes/notifications.py, app/api/v1/routes/projects.py, app/api/v1/routes/purchase.py, app/api/v1/routes/staking.py, app/api/v1/routes/tutorials.py, app/api/v1/routes/users.py, app/api/v1/routes/util.py, app/api/v1/routes/vesting.py, app/api/v1/routes/whitelist.py, app/main.py, app/test/test_asset.py, app/test/test_example.py, app/test/test_whitelist.py, app/utils/db.py
- replace async def with def
- remove await
=> Remove async/await

app/api/v1/routes/asset.py
=> :add: caching to get_asset_balance

app/api/v1/routes/blockchain.py, docker-compose.yml
- reset main to safetynet
- added compose.yml notes for gunicorn and nginx-unit
- verified that recent PRs from noob/lui are included
=> add compose.yml notes

app/api/v1/routes/staking.py, app/config.py
- updated /staked to use unspent service
- added danaida config
=> replace staked with unspent logic

app/api/v1/routes/events.py, app/api/v1/routes/staking.py, app/api/v1/routes/util.py, app/api/v1/routes/vesting.py
=> :fix: unit tests

app/api/v1/routes/asset.py, app/api/v1/routes/blockchain.py, app/api/v1/routes/staking.py, app/api/v1/routes/whitelist.py, docker-compose.yml
- added incentive
- unspent service updates
=> egio updates

app/api/v1/routes/staking.py
=> :add: staked-all endpoint

app/api/v1/routes/staking.py
- consolidate all 3 staking tokens
=> upd staked endpoint

app/api/v1/routes/staking.py
:fix: name reference before assignment
=> :fix: staked renamed

app/api/v1/routes/staking.py
=> :fix: staked renamed again

app/api/v1/routes/staking.py
=> :add: tokenName to staked response fix

app/api/v1/routes/blockchain.py, app/api/v1/routes/staking.py
- penalty for staking-v2
- fix in_circulation endpoints
=> :fix: penalty for paideia

app/api/v1/routes/announcements.py, app/api/v1/routes/auth.py, app/api/v1/routes/contribution.py, app/api/v1/routes/faq.py, app/api/v1/routes/jobs.py, app/api/v1/routes/notifications.py, app/api/v1/routes/projects.py, app/api/v1/routes/staking.py, app/api/v1/routes/tutorials.py, app/api/v1/routes/users.py, app/api/v1/routes/whitelist.py, app/core/auth.py
If someone is loading the dashboard or anything, everything else (including the CMS) will be blocked. 
CMS doesn't take any time to load by itself. Setup CMS to respond even if explorer and other parts of the API are running slow
=> :update: make cms sync

app/api/v1/routes/blockchain.py
- route to replace all needed measures on token page
=> new tokenStats route

app/main.py
time calls to help troubleshoot
=> add timer to request middleware

app/api/v1/routes/blockchain.py
- removed dup endpoint
- updated sql query to match upspent service work
=> upd sql from unspent

app/api/v1/routes/blockchain.py
- normalize calcs to include decimals
=> upd incirc calc

app/api/v1/routes/blockchain.py
- normalize values to include decimals
=> upd tokenomics

app/api/v1/routes/staking.py, app/requirements.txt
- Updated paideia-contracts in requirements.txt
- Enabled backend config for egiov2 staking
=> paideia-contracts version and config

app/api/v1/routes/vesting.py
```json
{
"addresses": [
"string"
]
}
```
=> :update: vesting/v1 handles multiple addresses

app/api/v1/routes/asset.py
- assets and balances
- rework structure of response
=> add new asset endpoint

app/api/v1/routes/asset.py
- final tokens/token_alt updates
=> upd decimals, type and price

app/api/v1/routes/asset.py
=> upd balances

app/api/v1/routes/asset.py
- upd structure to recommendation by noob
=> upd balances structure

app/api/v1/routes/asset.py, app/api/v1/routes/blockchain.py
- redirect balance to use balances endpoint
- remove explorer from /tokenInfo route
=> upd tokenInfo and balances

app/requirements.txt, docker-compose.yml
=> added gunicorn and included in compose.yml

app/api/v1/routes/asset.py, app/api/v1/routes/blockchain.py, app/requirements.txt, docker-compose.yml
- using gunicorn
- unspent asset/ba/ance/{address}
=> upd gunicorn

app/api/v1/routes/staking.py, app/api/v1/routes/vesting.py
=> :fix: ergopay requests

app/api/v1/routes/staking.py
- upd staking config to avoid explorer
- shunt stakedv2 route, but left code for reference
=> staking changes danaides

app/api/v1/routes/staking.py
- calc penalty from ergovalue
- rollback few danaides calls
=> upd staking

app/api/v1/routes/staking.py, app/cache/cache.py
- fix Decimal cast when setting in cache (this may only happen in testing if cache isn't cleared after some updates)
- was dividing token by decimal places incorrectly
=> upd staking amt decimal cast and calc

app/api/v1/routes/staking.py, app/cache/cache.py
- fix decimal calce
- fix json for staked output json
=> staking tweaks for newest danaides

app/api/v1/routes/asset.py, app/api/v1/routes/staking.py, app/api/v1/routes/vesting.py
- upd wording for unable to handle nft
=> convert str to int on  /staked

app/api/v1/routes/staking.py
=> :fix: staked value string issue

app/api/v1/routes/staking.py
converted "staked" endpoints to use danaides instead of explorer
- staking/staked
- staking/{project}/staked
- staking/staked-all
=> updated 3 staking endpoints

app/api/v1/routes/asset.py, app/api/v1/routes/blockchain.py, app/api/v1/routes/staking.py, app/api/v1/routes/vesting.py, app/api/v1/routes/whitelist.py, app/requirements.txt
- upd remaining functions calling explorer
- upds to allow neta staking
=> neta and explorer updates

app/api/v1/routes/whitelist.py
- backend changes for https://github.com/ergo-pad/ergopad-api/issues/436
=> :update: changes for early bird round

app/api/v1/routes/staking.py, app/api/v1/routes/whitelist.py
- restructured result
- added penalty to v1 contracts
=> staked all tweak

app/api/v1/routes/staking.py, docker-compose.yml
- improved performance
- reverting to uvicorn as asgi server (stability)
=> Staking status perf

app/api/v1/routes/asset.py, app/api/v1/routes/blockchain.py, app/api/v1/routes/events.py, app/api/v1/routes/purchase.py, app/api/v1/routes/staking.py, app/api/v1/routes/util.py, app/api/v1/routes/vesting.py, app/api/v1/routes/whitelist.py, app/main.py, app/test/test_asset.py, app/test/test_example.py, app/test/test_whitelist.py
=> remove async and await

app/api/v1/routes/blockchain.py, app/api/v1/routes/staking.py
- upd blockchain call to avoid mempool for unstake (reason: ergo explorer timeouts)
- upd unstake logic
=> Rmv exp from unstake

app/api/v1/routes/whitelist.py
- should fix https://www.ergopad.io/whitelist/auctionhouse/seed
=> :fix: null check for early_bird whitelist
